# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Example' do

  use_frameworks!

  # Pods for Example

  pod 'YuiToast', :path => '../'
  pod 'Reveal-SDK', "~> 24", :configurations => ['Debug']
  
end
